<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mlascoreclashnewtest"
 *
 * Auto generated by Extension Builder 2016-05-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MLA scoreclash',
	'description' => '',
	'category' => 'distribution',
	'author' => 'Michel Lavat',
	'author_email' => 'michellavat@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);